---
  - name: install nginx
    action: yum name=nginx

  - shell: mkdir /etc/nginx/sites-available
  - shell: mkdir /etc/nginx/sites-default

  - name: write sites-available configs
    action: template src=templates/default.j2 dest=/etc/nginx/sites-available/default

  - name: write nginx.conf
    action: template src=templates/nginx.conf.j2 dest=/etc/nginx/nginx.conf
    notify:
      - restart nginx

  - name: delete default vhost
    action: file path=/etc/nginx/sites-enabled/default state=absent
    notify:
      - restart nginx
